name: CD

# only build on main branch
on:
  push:
    branches:
      - main

# project specific config
env:
  USER_NAME: repraze
  IMAGE_NAME: repraze-parking

# create docker image
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.REGISTRY_PAT }}" | docker login ghcr.io -u $USER_NAME --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/$USER_NAME/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker image tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker image push $IMAGE_ID:$VERSION
